Add WSIMOD
protontypes/open-sustainable-technology pull request #609
Opened 2024-05-31 07:14 UTC by Ly0n

**Insert URLs to the project here:** https://github.com/ImperialCollegeLondon/wsi

- [x] The projects is active, documented, open source licensed, shows usage from external parties and is directly targeting environmental sustainability. Find more details in the [Contribution Guide](https://opensustain.tech/contributing/).

_All issues labeled as **Good First Issue** of the project listed on [OpenSustain.tech](https://opensustain.tech/) will be visible on [ClimateTriage.com](https://climatetriage.com/). This is a great way to welcome new community members to your project._

All projects listed will be posted on our [Mastodon channel](https://mastodon.social/@opensustaintech)

2024-06-03 17:15 UTC, andrew requested changes
typo

2024-06-03 18:54 UTC, andrew approved these changes

2024-06-04 06:29 UTC, Ly0n commented
@barneydobson @dalonsoa

2024-06-04 06:30 UTC, Ly0n commented
Provides a message passing interface to enable different subsystem models to communicate water flux and water quality information between each other, and self-contained representations of the key parts of the water cycle. https://github.com/ImperialCollegeLondon/wsi

2024-06-04 06:30 UTC, merged