Add ColOpenData
protontypes/open-sustainable-technology pull request #730
Opened 2024-07-31 09:48 UTC by Ly0n

**Insert URLs to the project here:** https://github.com/epiverse-trace/ColOpenData

- [x] The projects is active, documented, open source licensed, shows usage from external parties and is directly targeting environmental sustainability. Find more details in the [Contribution Guide](https://opensustain.tech/contributing/).

_All issues labeled as **Good First Issue** of the project listed on [OpenSustain.tech](https://opensustain.tech/) will be visible on [ClimateTriage.com](https://climatetriage.com/). This is a great way to welcome new community members to your project._

All projects listed will be posted on our [Mastodon channel](https://mastodon.social/@opensustaintech)

2024-08-01 13:52 UTC, andrew requested changes

2024-08-01 13:52 UTC, andrew commented on README.md
> +- [ColOpenData](https://github.com/epiverse-trace/ColOpenData) -  A package that acquires and wrangles Colombian socioeconomic, geospatial and climate data.
```suggestion
- [ColOpenData](https://github.com/epiverse-trace/ColOpenData) - A package that acquires and wrangles Colombian socioeconomic, geospatial and climate data.
```

2024-08-02 10:20 UTC, andrew approved these changes

2024-08-02 19:30 UTC, Ly0n commented
@jd-otero  @macataci

2024-08-02 19:30 UTC, merged